### ISSUE TITLE
qc_step - track check

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OceanObsQC#10]
sort profiles from each ship and floating buoys in time, remove profiles that would have resulted from an unrealistic speed.
- max of 15 m/s for ships, 2m/s for buoys
- need to exclude: air dropped XBT, ships with identical identifiers, profiles with generic 'SHIP' or '0' identifier

_implemented in the EN3/EN4 checks_

**Comment by hyunchul386** [comment]
The new vector obs_rej aggregates all rejected obs data with tag of the QC check type in hour variable.
So, in obs_rej, the hour is not real one, but tag of rejected-check-type.

**Comment by travissluka** [comment]
abandoning all issues from old UMD Hybrid-GODAS
