### ISSUE TITLE
qc_step - spike check

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OceanObsQC#5]
calculate the gradient of the values with depth, remove spikes:

- threshold gradient for removing surface spikes
- threshold gradient for removing small bottom spikes; minimum profile depth for applying this fix
   	tbsmax = 0.06
	   	zbsmin = 500.0
	   	ntbspk = 0
	
- settings for removing spikes other than at surface or bottom; counter
	   	dtroff = 2.0
	   	dtsgn = -1.0
	   	ntfspk = 0

**Comment by travissluka** [comment]
**surface spikes**
```
if (abs((pt(1)-pt(2))/(pz(2)-pz(1))) .gt. t1smax) then
  pt(1)=pt(2)
```

**bottom spikes**
``` 
if (abs((pt(np-1)-pt(np))/(pz(np)-pz(np-1))) .gt. tbsmax) then
  np = np - 1
```

**Comment by hyunchul386** [comment]
For temperature and salinity profile, checking the surface and bottom spikiness is done in qc_profile.
Now, surface spikiness check reject the bad profile and the bottom spikiness check can reject only bottom one.

**Comment by travissluka** [comment]
abandoning all issues from old UMD Hybrid-GODAS
