### ISSUE TITLE
qc_step - constants and offsets

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OceanObsQC#7]
check for profiles with constant values, or a definite constant offset.

current GODAS:
- threshold for removing profiles with constant and deep offsets
	         (modified below according to profile type and location)
	   	ddtmx = 0.5
	   	ncoff = 0
	   	ndoff = 0
	
- parameters for identifying and deleting bad ~constant profiles
	   	trmin = 0.05
	   	trlatn = 60.0
	   	trlats = -60.0
	   	trz = 100.0
	   	ncnst = 0
	
- parameters for identifying and truncating constant bottom sections of
	         profiles (appears limited to near-shore bathys)
	   	dtcnst = 0.12
	   	dzcnst = 150.0
	   	zcnst = 1000.0
	   	ndcnst = 0

**Comment by hyunchul386** [comment]
Near constant vertical profile is checked in qc_profile.
Now default latitude is 60N and 60S, ant can bu adjusted in the namelist parameter

**Comment by travissluka** [comment]
abandoning all issues from old UMD Hybrid-GODAS
