### ISSUE TITLE
qc_step - noisy profiles

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OceanObsQC#8]
current godas:
threshhold for rms of (t(k-1)-t(k)) for deleting noise profiles; 	        (modified below according to profile type and locations,         like Gulf Stream, GoM, Indonesian throughflow regions etc,
         Cheking bin and histo at each profile to reference data)	       
- dtrmx = 1.75
- nnoise = 0

**Comment by hyunchul386** [comment]
For temperature and salinity vertical gradient and its rms, the noisiness is checked in qc_profile

**Comment by travissluka** [comment]
abandoning all issues from old UMD Hybrid-GODAS
